// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Eiw7ktoGyBurTki8J8VdVymQ5--WMI0',
    appId: '1:195253129678:web:3ef02ad49f360bf45b5b9f',
    messagingSenderId: '195253129678',
    projectId: 'farm-management-d6cad',
    authDomain: 'farm-management-d6cad.firebaseapp.com',
    databaseURL: 'https://farm-management-d6cad-default-rtdb.firebaseio.com',
    storageBucket: 'farm-management-d6cad.appspot.com',
    measurementId: 'G-J22T0W890N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPJ-t9TWCnrNrGSkXSTpAwPJN91Olua4',
    appId: '1:195253129678:android:af18c9e4323d52d75b5b9f',
    messagingSenderId: '195253129678',
    projectId: 'farm-management-d6cad',
    databaseURL: 'https://farm-management-d6cad-default-rtdb.firebaseio.com',
    storageBucket: 'farm-management-d6cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtGxLipIuLG24CNo-Buh5WWKSbP6srzB8',
    appId: '1:195253129678:ios:e20675f5fec510c15b5b9f',
    messagingSenderId: '195253129678',
    projectId: 'farm-management-d6cad',
    databaseURL: 'https://farm-management-d6cad-default-rtdb.firebaseio.com',
    storageBucket: 'farm-management-d6cad.appspot.com',
    iosClientId: '195253129678-b3i8llio6lfuin0q8aee703ctkt01194.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
